# Generated by Django 4.1.4 on 2022-12-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('datetime_start', models.DateTimeField()),
                ('unit_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cashless', models.BooleanField()),
                ('is_weekend_open', models.BooleanField()),
                ('is_sunday_open', models.BooleanField()),
                ('mon_fri_start_hour', models.IntegerField()),
                ('mon_fri_start_min', models.IntegerField()),
                ('mon_fri_end_hour', models.IntegerField()),
                ('mon_fri_end_min', models.IntegerField()),
                ('sat_sun_start_hour', models.IntegerField()),
                ('sat_sun_start_min', models.IntegerField()),
                ('sat_sun_end_hour', models.IntegerField()),
                ('sat_sun_end_min', models.IntegerField()),
                ('lunch_break_start_hour', models.IntegerField()),
                ('lunch_break_start_min', models.IntegerField()),
                ('lunch_break_end_hour', models.IntegerField()),
                ('lunch_break_end_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=20)),
                ('mfm_euro_available', models.BooleanField()),
                ('mfm_euro_work_hours', models.BooleanField()),
                ('mfm_euro_all_day', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('appointment_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.appointmentschedule')),
            ],
        ),
    ]
