# Generated by Django 4.1.4 on 2022-12-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appointment_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
    ]
